using System;

namespace CompilersFinalProject.Compiler
{
    public enum OperationTypeDefinition
    {
        op_push = 1,
        op_pushi = 2,
        op_pop = 3,
        op_popi = 4,
        op_add = 5,
        op_sub = 6,
        op_end = 7,
        op_mul = 8,
        op_div = 9,
        op_and = 10,
        op_or = 11,
        op_xor = 12,
        op_shl = 13,
        op_shr = 14,
        op_not = 15,
        op_neg = 16,
        op_fadd = 17,
        op_fend = 18,
        op_fmul = 19,
        op_fdiv = 20,
        op_fneg = 21,
        op_fnot = 22,
        op_fcon = 23,
        op_icon = 24,
        op_exch = 25,
        op_eql = 26,
        op_neq = 27,
        op_lss = 28,
        op_gtr = 29,
        op_leq = 30,
        op_geq = 31,
        op_feql = 32,
        op_fneq = 33,
        op_flss = 34,
        op_fgtr = 35,
        op_fleg = 36,
        op_fgeq = 37,
        op_pr = 38,
        op_stop = 39,
        op_dup = 40,
        op_jmp = 41,
        op_fjmp = 42,
        op_tjmp = 43,
        op_popa = 44,
        op_pusha = 45,
        op_out = 46,
        op_pushr = 47
    }
}